name: "🚀 publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github v2"
        uses: actions/checkout@v2

      - name: "Setup node env"
        uses: actions/setup-node@v2
        with:
          node-version: 18.16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: pack
        run: npm pack --dry-run

      - name: publish
        run: npm publish --registry=https://npm.pkg.github.com

        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}